<h1 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all">Contador de Lineas</h1>
<br/>
<h3>Administrador</h3>

<div class="formulario">
	<ul>
		<li><a href="<?= $this->baseUrl('usuario/add')?>">Crear Usuario</a></li>
		<li><a href="<?= $this->baseUrl('configuracion/index')?>">Crear Configuracion</a></li>
		<li><a href="<?= $this->baseUrl('contador/index')?>">Actualizar Objetivos</a></li>
	</ul>
</div>